[package]
name = "memmet"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = "4.5.36"
directories = "6.0.0"
ffmpeg-sidecar = "2.0.5"
ffprobe = "0.4.0"
itertools = "0.14.0"
num2words = "1.2.0"
serde = "1.0.219"
serde_json = "1.0.140"
