[package]
name = "memmet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive", "string"] }
ffmpeg-sidecar = "2.0.5"
ffprobe = "0.4.0"
num2words = "1.2.0"
